"""initial schema: bots, content_items, social_credentials, pipeline_logs

Revision ID: 78b8c9904131
Revises: 
Create Date: 2026-02-11 19:52:28.714285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78b8c9904131'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('niche', sa.String(length=100), nullable=False),
    sa.Column('niche_description', sa.Text(), nullable=False),
    sa.Column('content_style', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('videos_per_day', sa.Integer(), nullable=False),
    sa.Column('posting_schedule', sa.JSON(), nullable=True),
    sa.Column('use_trends', sa.Boolean(), nullable=False),
    sa.Column('custom_prompts', sa.JSON(), nullable=True),
    sa.Column('video_provider', sa.String(length=20), nullable=False),
    sa.Column('video_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('video_aspect_ratio', sa.String(length=10), nullable=False),
    sa.Column('gemini_api_key', sa.Text(), nullable=True),
    sa.Column('gemini_model', sa.String(length=50), nullable=False),
    sa.Column('telegram_chat_id', sa.String(length=50), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('script_system_prompt', sa.Text(), nullable=False),
    sa.Column('trend_sources', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('content_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('trend_topic', sa.Text(), nullable=True),
    sa.Column('custom_prompt', sa.Text(), nullable=True),
    sa.Column('script', sa.Text(), nullable=True),
    sa.Column('script_model', sa.String(length=50), nullable=True),
    sa.Column('video_prompt', sa.Text(), nullable=True),
    sa.Column('video_provider', sa.String(length=20), nullable=True),
    sa.Column('video_task_id', sa.String(length=200), nullable=True),
    sa.Column('video_file_path', sa.Text(), nullable=True),
    sa.Column('video_url', sa.Text(), nullable=True),
    sa.Column('video_duration', sa.Float(), nullable=True),
    sa.Column('description_instagram', sa.Text(), nullable=True),
    sa.Column('description_youtube', sa.Text(), nullable=True),
    sa.Column('description_tiktok', sa.Text(), nullable=True),
    sa.Column('telegram_message_id', sa.Integer(), nullable=True),
    sa.Column('approval_status', sa.String(length=20), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.String(length=100), nullable=True),
    sa.Column('publish_instagram_id', sa.String(length=100), nullable=True),
    sa.Column('publish_youtube_id', sa.String(length=100), nullable=True),
    sa.Column('publish_tiktok_id', sa.String(length=100), nullable=True),
    sa.Column('publish_instagram_at', sa.DateTime(), nullable=True),
    sa.Column('publish_youtube_at', sa.DateTime(), nullable=True),
    sa.Column('publish_tiktok_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('social_credentials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('platform_user_id', sa.String(length=100), nullable=True),
    sa.Column('platform_username', sa.String(length=100), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bot_id', 'platform', name='uq_bot_platform')
    )
    op.create_table('pipeline_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ),
    sa.ForeignKeyConstraint(['content_id'], ['content_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pipeline_logs')
    op.drop_table('social_credentials')
    op.drop_table('content_items')
    op.drop_table('bots')
    # ### end Alembic commands ###
