"""add story arc columns

Revision ID: b0f8d3bce09e
Revises: e78ec5fdea78
Create Date: 2026-02-12 12:07:09.767605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0f8d3bce09e'
down_revision: Union[str, Sequence[str], None] = 'e78ec5fdea78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bots', sa.Column('story_arc_enabled', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('bots', sa.Column('story_arc_chapters', sa.Integer(), server_default='3', nullable=False))
    op.add_column('content_items', sa.Column('story_arc_id', sa.String(length=50), nullable=True))
    op.add_column('content_items', sa.Column('story_arc_chapter', sa.Integer(), nullable=True))
    op.add_column('content_items', sa.Column('story_arc_total', sa.Integer(), nullable=True))
    op.add_column('content_items', sa.Column('story_arc_premise', sa.Text(), nullable=True))
    op.create_index(op.f('ix_content_items_story_arc_id'), 'content_items', ['story_arc_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_content_items_story_arc_id'), table_name='content_items')
    op.drop_column('content_items', 'story_arc_premise')
    op.drop_column('content_items', 'story_arc_total')
    op.drop_column('content_items', 'story_arc_chapter')
    op.drop_column('content_items', 'story_arc_id')
    op.drop_column('bots', 'story_arc_chapters')
    op.drop_column('bots', 'story_arc_enabled')
    # ### end Alembic commands ###
