"""add production_config and production_mode

Revision ID: dcda735a084c
Revises: 0a3fb02a5958
Create Date: 2026-02-12 19:12:26.369567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcda735a084c'
down_revision: Union[str, Sequence[str], None] = '0a3fb02a5958'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bots', sa.Column('production_mode', sa.String(length=20), nullable=False, server_default='standard'))
    op.add_column('bots', sa.Column('production_config', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bots', 'production_config')
    op.drop_column('bots', 'production_mode')
    # ### end Alembic commands ###
