"""add brand_style to bots

Revision ID: e78ec5fdea78
Revises: 45dcac9c2dbe
Create Date: 2026-02-11 22:12:22.279483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e78ec5fdea78'
down_revision: Union[str, Sequence[str], None] = '45dcac9c2dbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bots', sa.Column('brand_style', sa.Text(), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bots', 'brand_style')
    # ### end Alembic commands ###
